### ISSUE TITLE
CSV Upload Bug: line contains NULL byte

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/logbook#24]
```
Internal Server Error: /upload/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/braces/views/_access.py", line 98, in dispatch
    request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/app/catalog/views.py", line 52, in form_valid
    counts  = form.save()
  File "/app/catalog/forms.py", line 74, in save
    counts  = parser.parse(dataset)
  File "/app/catalog/parser.py", line 135, in parse
    reader = csv.DictReader(data, encoding=detect_encoding(data))
  File "/app/.heroku/python/lib/python2.7/site-packages/unicodecsv/py2.py", line 208, in __init__
    if self.fieldnames is not None:
  File "/app/.heroku/python/lib/python2.7/csv.py", line 90, in fieldnames
    self._fieldnames = self.reader.next()
  File "/app/.heroku/python/lib/python2.7/site-packages/unicodecsv/py2.py", line 117, in next
    row = self.reader.next()
Error: line contains NULL byte
```

**Comment by bbengfort** [comment]
@ojedatony1616 Do you think you could try to reproduce this error from what you were attempting to upload on Saturday, and send me how you did it?

**Comment by ojedatony1616** [comment]
@bbengfort Yes, I'll try a couple things we did that day and see what causes it.

**Comment by bbengfort** [comment]
@ojedatony1616 any more word on this?
